export const genres_list = [
    // Rock a jeho podžánry
    "Rock",
    "Alternative Rock",
    "Hard Rock",
    "Progressive Rock",
    "Psychedelic Rock",
    "Indie Rock",
    "Garage Rock",
    "Glam Rock",
    "Southern Rock",
    "Blues Rock",
    "Post-Rock",
    "Stoner Rock",
  
    // Metal a jeho podžánry
    "Heavy Metal",
    "Thrash Metal",
    "Death Metal",
    "Black Metal",
    "Doom Metal",
    "Power Metal",
    "Symphonic Metal",
    "Progressive Metal",
    "Metalcore",
    "Deathcore",
    "Folk Metal",
    "Viking Metal",
    "Industrial Metal",
    "Nu Metal",
    "Gothic Metal",
    "Sludge Metal",
    "Groove Metal",
  
    // Punk a hardcore
    "Punk Rock",
    "Hardcore Punk",
    "Post-Punk",
    "Pop Punk",
    "Crust Punk",
    "Ska Punk",
    "Emo",
    "Screamo",
  
    // Elektronická hudba a EDM
    "Electronic",
    "House",
    "Techno",
    "Trance",
    "Drum and Bass",
    "Dubstep",
    "Synthwave",
    "Hardstyle",
    "Industrial",
    "Future Bass",
    "Psytrance",
    "Ambient",
    "Chillout",
    "Vaporwave",
    "Breakbeat",
  
    // Hip Hop, R&B, Rap
    "Hip Hop",
    "Rap",
    "Trap",
    "Old School Hip Hop",
    "Lo-Fi Hip Hop",
    "Gangsta Rap",
    "Conscious Rap",
    "Drill",
    "R&B",
    "Neo Soul",
    "Funk",
  
    // Jazz, Blues, Soul
    "Jazz",
    "Smooth Jazz",
    "Bebop",
    "Swing",
    "Big Band",
    "Blues",
    "Soul",
    "Gospel",
  
    // Pop a mainstreamová hudba
    "Pop",
    "Synthpop",
    "Indie Pop",
    "Dream Pop",
    "Bubblegum Pop",
    "K-Pop",
    "J-Pop",
    "Latin Pop",
  
    // Country a folk
    "Country",
    "Bluegrass",
    "Americana",
    "Folk",
    "Singer-Songwriter",
    "Celtic",
  
    // Reggae, ska, world music
    "Reggae",
    "Ska",
    "Dub",
    "Afrobeat",
    "Flamenco",
    "Latin",
    "Bossa Nova",
    "Salsa",
    "Tango",
    "Klezmer",
  
    // Experimentální a klasická hudba
    "Classical",
    "Opera",
    "Baroque",
    "Minimalism",
    "New Age",
    "Avant-Garde",
    "Postmodern",
    "Noise",
  
    // Soundtracky a speciální žánry
    "Soundtrack",
    "Video Game Music",
    "Musical",
    "Lo-Fi",
    "Chiptune",
    "Darkwave",
    "Gothic",
    "Drone"
  ];
  