export const mockProfiles = [
  {
    id: "1",
    name: "Karel Klátil",
    instrument: "Bass",
    genres: ["Jazz"],
    location: "Brno",
    age: 27,
    gender: "male",
    avatar: "https://i.pravatar.cc/150?img=70",
  },
  {
    id: "2",
    name: "Jakub Novák",
    instrument: "Drums",
    genres: ["Metal"],
    location: "Ostrava",
    age: 24,
    gender: "male",
    avatar: "https://i.pravatar.cc/150?img=11",
  },
  {
    id: "3",
    name: "Anička Bálková",
    instrument: "Vocal",
    genres: ["Pop"],
    location: "Praha",
    age: 22,
    gender: "female",
    avatar: "https://i.pravatar.cc/150?img=49",
  },
  {
    id: "4",
    name: "Petr Veselý",
    instrument: "Guitar",
    genres: ["Rock"],
    location: "Brno",
    age: 31,
    gender: "male",
    avatar: "https://i.pravatar.cc/150?img=52",
  },
]
