export const mockProfiles = [
  {
    id: "1",
    name: "Karel Klátil",
    instrument: "Bass Guitar",
    genres: ["Jazz"],
    location: "Brno",
    age: 60,
    gender: "male",
    avatar: "https://i.pravatar.cc/150?img=70",
  },
  {
    id: "2",
    name: "Jakub Novák",
    instrument: "Drums",
    genres: ["Metal"],
    location: "Ostrava",
    age: 32,
    gender: "male",
    avatar: "https://i.pravatar.cc/150?img=11",
  },
  {
    id: "3",
    name: "Anička Bohuvicová",
    instrument: "Vocal",
    genres: ["Pop"],
    location: "Praha",
    age: 22,
    gender: "female",
    avatar: "https://i.pravatar.cc/150?img=49",
  },
  {
    id: "4",
    name: "Petr Veselý",
    instrument: "Electric Guitar",
    genres: ["Rock"],
    location: "Brno",
    age: 31,
    gender: "male",
    avatar: "https://i.pravatar.cc/150?img=52",
  },
  {
    id: "5",
    name: "Jiří Nastatek",
    instrument: "Accordion",
    genres: ["Metalcore"],
    location: "Czech republic",
    age: 27,
    gender: "male",
    avatar: "https://i.pravatar.cc/150?img=68",
  },
  {
    id: "6",
    name: "Anežka Karásková",
    instrument: "Drums",
    genres: ["Metal"],
    location: "Ostrava",
    age: 24,
    gender: "female",
    avatar: "https://i.pravatar.cc/150?img=62",
  },
  {
    id: "7",
    name: "Izabela Pokuřná",
    instrument: "Harmonica",
    genres: ["Blues"],
    location: "Praha",
    age: 22,
    gender: "female",
    avatar: "https://i.pravatar.cc/150?img=39",
  },
]
